### ISSUE TITLE
Volunteering Page Issue

### ISSUE THREAD

**Issue by witchkrafte** [HazimAr/School-Simplified#43]
When you switch between teams on the volunteering page, there's a sort-of weird split-second loading screen that appears for each image. Seeing if anything can be done about it.

**Comment by RashmitShrestha** [comment]
That happened to me but it went away after a few clicks; I think it's cause my computer's slow so it can't render images super fast so it might be solved with like a different type of screen switching animation or it just might depend on the client's computer

**Comment by LeftistTachyon** [comment]
> When you switch between teams on the volunteering page, there's a sort-of weird split-second loading screen that appears for each image. Seeing if anything can be done about it.

My guess is because images load kinda slow.

**Comment by LeftistTachyon** [comment]
> That happened to me but it went away after a few clicks; I think it's cause my computer's slow so it can't render images super fast so it might be solved with like a different type of screen switching animation or it just might depend on the client's computer

This would be because your browser caches the images after you cycle through them once, so there's no need to download the entire image, skipping the loading phase

So no glitchy load thing

**Comment by LeftistTachyon** [comment]
@RashmitShrestha you fixed this bug in the cringiest method possible

:anger:

**Comment by LeftistTachyon** [comment]
Fix rejected because:
 - Removed animations
 - No autoscroll
 - Sometimes when hit arrow, doesn't move to next slide
 - ~~code is cring bro~~

**Comment by LeftistTachyon** [comment]
Get a fiber optic cable lol

**Comment by RashmitShrestha** [comment]
because my code is cringe, can someone check if the images are preloading well? 

i made a change to the rotating panel file so that the image files will preload without the use of fiber optic cables thankfully 

it seems to be loading (after that initial loading sequence) for now; my code can def be refactored, maybe like a compenntDidUpdate() addition will do the trick but I'm hoping it works for your computers and the concept makes sense
