### ISSUE TITLE
Header Drop Down Menu

### ISSUE THREAD

**Issue by harrychow04** [HazimAr/School-Simplified#56]
Add a 3 line hamburger drop-down menu on the top right of the header, then I would reprioritize what is in the header, a "Home" button isn't needed as the logo itself brings you home, so it should be 

"About Us, Services, Volunteer, Contact Us" followed by drop down menu

**Comment by LeftistTachyon** [comment]
Can you explain the necessity to have this hamburger menu? It seems a little unnecessary given that we have links as it is

**Comment by RashmitShrestha** [comment]
I agree with @LeftistTachyon on this, furthermore, I think a larger problem is the drop-down nav links themselves, strictly for **About Us** and **Services**, since on hover they don't have the underline so it's a bit strange.

I can see a possible solution being that the drop-down list is shown on hover and on click so that users will know for sure that there's more content from that link

**Comment by harrychow04** [comment]
dont rlly need it just find a way for "Support Us" to be at the top as well

**Comment by HazimAr** [comment]
@harrychow04 what is the support us going to be. Ethan removed the donate page

**Comment by IsamarZhu** [comment]
maybe we could put support us under the "about us" dropdown in the header?

**Comment by HazimAr** [comment]
> maybe we could put support us under the "about us" dropdown in the header?

No more donate page

**Comment by harrychow04** [comment]
wdym no more donate page

**Comment by LeftistTachyon** [comment]
> wdym no more donate page

@harrychow04, check commit e5ad593730aada89421b7534bc4b9f3ac3a42abd
